### ISSUE TITLE
Bug in Objects section 

### ISSUE THREAD

**Issue by SkillerCMP** [PixelRick/CyberpunkSaveEditor#11]
If you have more then 1 Section open, you get unviewable Objects. 
![image](https://user-images.githubusercontent.com/76823351/103970121-bd356e00-5124-11eb-93da-6169f9e7c14e.png)

Possible Auto close if u try to open another Section ?

**Comment by PixelRick** [comment]
This widget has been reworked and no longer shows this early clipping bug.
