### ISSUE TITLE
[Feature request] Expand and Collapse - Fields/idx

### ISSUE THREAD

**Issue by SkillerCMP** [PixelRick/CyberpunkSaveEditor#12]
Having the ability to Expand or Collapse the Fields/idxs 
Collapsed Fields would only show the Names Values until clicked on 
Collapsed Index would Only Show the Idx Values until clicked on 
Maybe Adding also Collapse/Expand all

Having everything collapsed at the start 
![image](https://user-images.githubusercontent.com/76823351/103970755-3a151780-5126-11eb-872d-634c757fcf4f.png)

**Comment by PixelRick** [comment]
Values for which the widget does not fit in a single line are now collapsible and collapsed by default in v0.5.2-alpha
Please review the change to know whether this issue can be closed or not.

**Comment by SkillerCMP** [comment]
you went above and beyond thanks :) Working good
