### ISSUE TITLE
Editing DataTrackingSystem had side effects

### ISSUE THREAD

**Issue by Psype** [PixelRick/CyberpunkSaveEditor#13]
Hey guys,

just to let you know, I edited `ScriptableSystemsContainer` > `DataTrackingSystem` as it seems to be partly linked to game success.
It broke my `ScriptableSystemsContainer` > `PreventionSystem`, and **all Fast travel points disappeared from the map**... 
(Can't use fast travel anymore and have to rediscover them all... Or load a backup ;) )

Cheers

**Comment by PixelRick** [comment]
Alright, I'm reworking the scriptable parts once more to bring stability and better testing.
The app always makes you a backup of the save, the file is named sav.old

**Comment by PixelRick** [comment]
A typo in v0.5.1-alpha caused corruption during the serialization of NodeRef properties. It maybe is what happened to you.
It'd be great if you can retry with the new release and report back the results here.

**Comment by PixelRick** [comment]
I close this issue as it seems to have been solved.
