### ISSUE TITLE
[Feature request] Add new entries inside arrays

### ISSUE THREAD

**Issue by ryselgh** [PixelRick/CyberpunkSaveEditor#14]
I noticed that you can add entries in structs but only remove them inside arrays.
Is it possible to extend arrays with new entries?
Thank you for your awesome work btw!

**Comment by PixelRick** [comment]
That's possible for dynamic arrays. There was an "insert new here" in the context menu at some point in time. I will reintroduce it.

**Comment by ryselgh** [comment]
Yes I thought about fixed arrays that would break the savegame, but there are some arrays that are clearly dynamic comparing multiple savegames. Maybe you can add a disclaimer about adding entries that would break the save if not knowing what you're doing

**Comment by PixelRick** [comment]
Available in the release v0.5.3-alpha. Please confirm that it is to your liking.

**Comment by ryselgh** [comment]
Actually what I mean is those elements in the appearence customization section:

![image](https://user-images.githubusercontent.com/5698155/104816761-5f3c1100-581d-11eb-90fe-2b5704d129fc.png)

I can assure you that the size is different between different savegames and would be extremely useful to add new elements inside those array.

**Comment by PixelRick** [comment]
I disabled adding/removing explicitly from this array until I knew better. I am going to enable it but the fact that the cnames are unknown may be a problem for users.

**Comment by ryselgh** [comment]
It's not necessary to know exactly cnames hashes, as users can reference them by comparing two savegames and add (or remove) appearence features to their character just by copying them from other saves as they are.
I can confirm that they are kind of unique IDs for those features. I managed to almost fully change my character gender by copying each cname and property values.

**Comment by PixelRick** [comment]
Forced push to fix a typo.

**Comment by ryselgh** [comment]
Tested and works perfectly, thanks!
