### ISSUE TITLE
Character voice (M/F) - no longer unknown byte at 02X

### ISSUE THREAD

**Issue by ryselgh** [PixelRick/CyberpunkSaveEditor#16]
I tested this byte and turns out it changes character's voiceover
00 = female voice
01 = male voice

![image](https://user-images.githubusercontent.com/5698155/104818896-9d8bfd00-582a-11eb-9ab8-56f8b391b031.png)

**Comment by PixelRick** [comment]
Thanks ! I will add that.

**Comment by sil3nci0** [comment]
Hi there,

I'm going crazy trying to completly change V's gender as i found another interesting byte

![image](https://user-images.githubusercontent.com/8971127/105630603-721c9a00-5e4a-11eb-9535-4ddd62c477f1.png)

seems, changig this one changes "gender" (no aspect):
01 - Male
00 - Female 

Checked in "metadata.9.json" and then it was saved with:
            "bodyGender": "Female",
            "brainGender": "Female",
Originaly it was "Male"

**Comment by PixelRick** [comment]
Well I should probably hide this one. Changing it isn't enough to change gender as transferring all the customization data between gender types does fail.

**Comment by sil3nci0** [comment]
Indeed... I tried and no luck. Tried transfer Female to a Male and  buggy resut. No body, nor legs, just floating original male head and arms.

**Comment by sil3nci0** [comment]
BTW, great job with this editor, thnx
