### ISSUE TITLE
Copy/Paste skin not copying between saves

### ISSUE THREAD

**Issue by FIying-Scotsman** [PixelRick/CyberpunkSaveEditor#19]
I read through the documentation and saw the copy-paste functionality is still experimental so this ticket is more a bug report but no matter what save type I use (level 50 to level 50 or level 10 to level 10) this functionality doesn't seem to do work. No value is changed between the saves.

Initially I tried copying the appearance from a level 50 save (just after the Ripperdoc story mission) to my level 10 (16 hour in) save and nothing happened as my appearance remained the same. 

Trying it with a seperate level 50 save and the level 50 save I was originally trying to use results in the same thing, as does using a modified, but older save of my own (using Arasaka's appearance editor to change my appearance to test this functionality out).

Initially I was given a "version mismatch" on the donor level 50 save but loading it up in-game and saving again, then quitting seemed to fix that so that is unlikely to be the cause of this failing when using my own saves (although it might have an influence on the donor saves not working). 

Is there a way to verify whether the appearance blob data was copied to the clipboard? As copying the appearance data across to my manual save, then trying to edit the save in Arasaka (for example changing the hair style which remained unchanged) would result in the game showing a black screen when trying to load the save.

**Comment by PixelRick** [comment]
Thanks for reporting back, indeed this feature was no longer working!
The customization editor data isn't reloaded with the pasted node, thus when saving the editor data overwrites what you pasted..

**Comment by PixelRick** [comment]
Seem to be ok now (v0.5.4-alpha.8). the way to verify it has been pasted is just to open the customization tab, it now reflects the changes instantly.

**Comment by PixelRick** [comment]
Reminder: it does not work between different genders.
Please reopen the issue if you happen to see another problem with this feature.
