### ISSUE TITLE
Fact delete button only works with the top fact item.

### ISSUE THREAD

**Issue by xitwid** [PixelRick/CyberpunkSaveEditor#20]
the fact delete button only works with the top fact item

**Comment by PixelRick** [comment]
Thanks for having opened an issue, i wouldn't have seen this bug. <3

**Comment by xitwid** [comment]
https://user-images.githubusercontent.com/39426656/106390156-f9a57280-6421-11eb-963c-5e7fb679a61e.mp4

here is a video to show u the bug

**Comment by PixelRick** [comment]
I fixed it already ^^, check the .11 release
