### ISSUE TITLE
About the upgrade of 1.23?

### ISSUE THREAD

**Issue by klinxun** [PixelRick/CyberpunkSaveEditor#26]
This SaveEditor does not work in the current version and requests that you upgrade it.

**Comment by PixelRick** [comment]
Yup, doing this asap.

**Comment by PixelRick** [comment]
I'll close it when it's done. Currently trying to use a dump made by a collaborator and it doesn't work, field order doesn't match.

**Comment by klinxun** [comment]
OK

**Comment by PixelRick** [comment]
Used my own dumper, worked. New CPSE version: v0.5.4-alpha.13.
If you encounter a problem with the update and your own save files, feel free to reopen this ticket and send me the files on discord.
Have a good day.

**Comment by klinxun** [comment]
![图片](https://user-images.githubusercontent.com/83117076/125156820-0cbf2a00-e19a-11eb-89af-bcf1f1462534.png)
Well, it came up with the above tips. I'm sorry my English is not very good. (Thanks for the translation software)

**Comment by PixelRick** [comment]
Did new dumps, indeed it's different from what I released last time.. no clue why. Check out the 13b.
Do you know if they did a small update without changing the version ?

**Comment by klinxun** [comment]
Sorry, I didn't give feedback on this issue in time. I haven't played 2077 for a while before.
o_o
