### ISSUE TITLE
New Constant Crash

### ISSUE THREAD

**Issue by RaimondLim** [PixelRick/CyberpunkSaveEditor#27]
The program crashed when using the 'New Constant' function.

**Comment by PixelRick** [comment]
looks like they are transitioning from one impl to another. Old stat classes are postfixed with _Deprecated, yet new ones have no properties. I'll try to fix this for the next weekend.. I have not enough time right now.

**Comment by PixelRick** [comment]
Well.. I took the time ^^ wasn't much after all.
Bug fixed with 0.5.4-alpha.14b.
