### ISSUE TITLE
Does not start, gave me an error (0xc000007b)

### ISSUE THREAD

**Issue by H8DCarnifeX** [PixelRick/CyberpunkSaveEditor#3]
I'm running the Tool on Win7, is it even supported for Win7?

**Comment by zao** [comment]
One hard blocker for Windows 7 is that Dear Imgui's win32 impl depends on xinput, which if built with a recent Windows SDK will depend on `xinput1_4.dll` which is not available on Windows 7 and cannot be transplanted onto the OS.

Citing `imgui_impl_win32.cpp`:
```
// Using XInput library for gamepad (with recent Windows SDK this may leads to executables which won't run on Windows 7)
#ifndef IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
#include <XInput.h>
```

On my Win7 test box the program runs successfully when built with `IMGUI_IMPL_WIN32_DISABLE_GAMEPAD` defined.
Don't forget to install the vcredist as mentioned in the Releases page: https://github.com/PixelRick/CyberpunkSaveEditor/releases/tag/v0.4.4-alpha.2

**Comment by zao** [comment]
![image](https://user-images.githubusercontent.com/260218/103355487-abadef80-4aae-11eb-80ec-a11611a0086c.png)

**Comment by PixelRick** [comment]
I can disable the gamepad !
