### ISSUE TITLE
With v0.5.4-Alpha-14b, Got This Error If I Opened Save File From Game Version 1.23

### ISSUE THREAD

**Issue by GaneJ** [PixelRick/CyberpunkSaveEditor#31]
With v0.5.4-Alpha-14b release, I got this error if I open save file from game version 1.23
![Screen1](https://user-images.githubusercontent.com/20153153/134198158-7b44ef43-3749-4d61-972d-861fe16b20ba.jpg)
:
![Screen2](https://user-images.githubusercontent.com/20153153/134198203-30c2fc96-2eb8-40f3-aa92-f130a79e0c95.jpg)

**Comment by GaneJ** [comment]
this is [my v1.23 save file](https://pixeldrain.com/u/op97TM9s)

**Comment by PixelRick** [comment]
I guess you are on PS4.
Each editor version is released with the types database (CObjectBPs.json) for only one game version.
Database for game v1.23 is accessible at this link: https://github.com/PixelRick/CyberpunkSaveEditor/blob/9f608573d3b838d9ec756336ce7bc1a1f064aa23/assets/CObjectBPs.json
Replace the one you have in the asset folder with it, and it should be good to go for 1.23 save files.
I didn't know PS4 would have deferred updates, I'll package multiple recent versions of the db in future updates of the editor.

**Comment by GaneJ** [comment]
Ahh, that explain a lot. I'm on windows 7. I tested your app to open my old save file (v1.23).

Database that you give me for v1.23 didn't worked, I got this error
![Screen02_00](https://user-images.githubusercontent.com/20153153/134301127-e4e6086f-faeb-4220-92b7-9bc5df9bd233.jpg)
![Screen02_01](https://user-images.githubusercontent.com/20153153/134301162-abe89ab5-d0c0-4f9d-8519-bcb5a2774328.jpg)
:
![Screen02_02](https://user-images.githubusercontent.com/20153153/134301187-f38472e3-ec72-4c7c-8b8d-23560cbc2a06.jpg)
![Screen02_03](https://user-images.githubusercontent.com/20153153/134301205-895ccac8-7d77-4984-baa4-b9a4acc59457.jpg)
![Screen02_04](https://user-images.githubusercontent.com/20153153/134301216-689d8482-cc66-4656-a133-e8748298d22c.jpg)
![Screen02_05](https://user-images.githubusercontent.com/20153153/134301223-a79be11d-8a1a-4dec-9952-423070f7c922.jpg)

**Comment by PixelRick** [comment]
First error causes the others.
Did you download the file via the download button ?
Here is the real direct link to the raw file: https://raw.githubusercontent.com/PixelRick/CyberpunkSaveEditor/9f608573d3b838d9ec756336ce7bc1a1f064aa23/assets/CObjectBPs.json

**Comment by GaneJ** [comment]
Did you download the file via the download button ?
Ah yes. I forgot.

I'm waiting for this "I'll package multiple recent versions of the db in future updates of the editor" in your next release.

Thanks @PixelRick

**Comment by PixelRick** [comment]
Possible solution requested in #36.
