### ISSUE TITLE
1.31 Update ?

### ISSUE THREAD

**Issue by DevEvil99** [PixelRick/CyberpunkSaveEditor#32]
can you update this mod to 1.31 bcuz I cant change the gender and other things, thanks

**Comment by Avalon-Ashes** [comment]
1111111

**Comment by PixelRick** [comment]
I'm moving for a new job, dunno how much time i will have yet.

**Comment by DevEvil99** [comment]
oh ok good luck

**Comment by PixelRick** [comment]
Skipped an update, now 1.5 (see #33).
