### ISSUE TITLE
Patch 1.5 - Update?

### ISSUE THREAD

**Issue by Sonatine1** [PixelRick/CyberpunkSaveEditor#33]
Hey!

First of all: Best Save editor for CP2077, imo.

Since Patch 1.5 has been released (which is actually a really nice Upgrade), will there be an update of the CPSE? I think they didn't change much of the file system, so maybe it's not even necessary - but I could be wrong (I'm anything but a coding / scripting pro).

Best regards
Sona

**Comment by thunderpants** [comment]
version hotfix 1.5 as also been relased just after 1.5.

**Comment by PixelRick** [comment]
I can finally work on it this week !

**Comment by thunderpants** [comment]
Yay ! :)

Thanks PixelRick !

**Comment by ZedzDed9792** [comment]
> I can finally work on it this week !

Oh please please try to add an inventory copy paste option my saves got corrupted (insta ctd) & lost 20h of play I'd kill for this feature

**Comment by Romire** [comment]
looking forward to it PR

**Comment by closer2thelung** [comment]
It seems for mesh swaps/edits, PReditor is not working at all on 1.5. Really looking forward to a new release!

From my limited testing:
* Setting chunkmask to 0's causes flatline -- unless you set to alwaysvisible (or is appearanceproxy)
* Setting meshes to alwaysvisible that are NOT 0'd out under chunkmask causes flatline

**Comment by Sonatine1** [comment]
Great news, that you're back on it. Such a powerful tool to even create weapons / armor etc. and edit so many things. Looking forward to it! :)

**Comment by PixelRick** [comment]
Some news: Everything except Systems (and thus entity editing) works again.
I prefer fixing it before release, but if it takes too long I'll do a release with Systems edits disabled tomorrow morning.
This way you'll at least have the inventory editor for the week-end.
