### ISSUE TITLE
Feature QOL: autofilter

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [PixelRick/CyberpunkSaveEditor#4]
when you get the time.. as a QoL could you make it that you can type in the list selection & it starts auto-matching items found? (auto filter as you type in more letters)
like typing in "Gren" would find & match any items Starting or ending with "Gren" EG list all Grenades only etc...

![Screen Shot 2020-12-31 at 7 31 10 am](https://user-images.githubusercontent.com/2242880/103379994-a21e9900-4b3b-11eb-9ecc-3ddd27f81e16.jpg)

**Comment by PixelRick** [comment]
It has been implemented with non thoroughly reviewed external code, but it's still enough to close this enhancement issue.
If a misbehavior of the widget happens please open a new bug issue.
