### ISSUE TITLE
System Crash While Loading File

### ISSUE THREAD

**Issue by UjwalReddy267** [PixelRick/CyberpunkSaveEditor#41]
Whole OS crashes when loading a save file. Cyberpunk Version 1.6. Windows 11.

**Comment by PixelRick** [comment]
Ehh, weird, a crashing app shouldn't crash the OS.
I have to update some stuff anyway for 1.6, but it's rush time at work so dunno when I'll do it :/

**Comment by wolfeKS** [comment]
Having this issue as well, also crashes my entire PC when loading file. Memory usage goes to maximum, then black screen, then forced to hard reset PC. I'm only on Windows 10 64 bit though, not Windows 11.

**Comment by Senfee-Cheng** [comment]
I hope you can take some time to update. 1.6 needs you

**Comment by Senfee-Cheng** [comment]
> Ehh, weird, a crashing app shouldn't crash the OS. I have to update some stuff anyway for 1.6, but it's rush time at work so dunno when I'll do it :/

I hope you can take some time to update. 1.6 needs you

**Comment by UjwalReddy267** [comment]
> Having this issue as well, also crashes my entire PC when loading file. Memory usage goes to maximum, then black screen, then forced to hard reset PC. I'm only on Windows 10 64 bit though, not Windows 11.

Same thing happens to me. However, this does not happen for an early game file

**Comment by Lanfrancodeifranchi** [comment]
I see this notification when I open the save file: could't load node_t ScriptableSystemsContainer
reason:CObject::serialize_in: serial fild clothingVisualsInfo has different type (array:game SSlotVisualInfo) than bp's (array:gameSSlotVisualInfo)

**Comment by fade-out-0770** [comment]
> Ehh, weird, a crashing app shouldn't crash the OS. I have to update some stuff anyway for 1.6, but it's rush time at work so dunno when I'll do it :/

Please update it at your convenience.😭😭😭

**Comment by ZC1DX1** [comment]
is powerful tool,please upgrade with 1.6

**Comment by pauld010** [comment]
Thanks for your work, waiting the update with patience :D

**Comment by PixelRick** [comment]
I updated the script types and identified the crash reason:
![image](https://user-images.githubusercontent.com/5144946/193406187-69e88894-9dc4-4b0b-89ce-ccad10251a24.png)
Looks like they modified their Item serializer so I have a bit of reversing to do to fix it (they are not serialized the same way as the script-types). I am starting now and then little break between 12 and 14 UTC. I will keep you updated if I stumble across other problems, otherwise it should be manageable to push a release in the evening.

**Comment by PixelRick** [comment]
Fixed and published: [Release v0.6.0-alpha.1](https://github.com/PixelRick/CyberpunkSaveEditor/releases/tag/v0.6.0-alpha.1)
Thanks for your support, and sorry for the late update.
