### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by x1unix** [PixelRick/CyberpunkSaveEditor#42]
When I'm trying to load my savegame file, process starts eating all my RAM causing OS to freeze. For example CyberCAT-SimpleGUI loads it just fine so I believe it might be a memory leak issue.

Attaching my savegame for testing.

[ManualSave-34.zip](https://github.com/PixelRick/CyberpunkSaveEditor/files/9592785/ManualSave-34.zip)

**Comment by PixelRick** [comment]
Duplicate #41.
Gonna update for 1.6 + investigate the leak that shouldn't happen anyway.
