### ISSUE TITLE
Unable to build solution - 0.6.0 alpha 0

### ISSUE THREAD

**Issue by LostLogic** [PixelRick/CyberpunkSaveEditor#43]
Just wanted to let you know that I'm getting the following errors when building as Release, Release with Debug and Debug:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced project '..\external\rttr.vcxproj' does not exist.	tdb_editor	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2066	
Error	C1083	Cannot open include file: 'winfsp/winfsp.h': No such file or directory	cpfs_winfsp	C:\Users\lostl\GitHub\CyberpunkSaveEditor-0.6.0-alpha\source\cpfs_winfsp\winfsp.h	5	
Error	C1083	Cannot open include file: 'winfsp/winfsp.h': No such file or directory	cpfs_winfsp	C:\Users\lostl\GitHub\CyberpunkSaveEditor-0.6.0-alpha\source\cpfs_winfsp\main.cpp	10	
Error	C1083	Cannot open include file: 'winfsp/winfsp.h': No such file or directory	cpfs_winfsp	C:\Users\lostl\GitHub\CyberpunkSaveEditor-0.6.0-alpha\source\cpfs_winfsp\utils.hpp	4	
Error	C1083	Cannot open include file: 'redx/io/file_stream.hpp': No such file or directory	tdb_editor	C:\Users\lostl\GitHub\CyberpunkSaveEditor-0.6.0-alpha\source\redx\tweakdb\tweakdb.hpp	12	
Error	C1083	Cannot open include file: 'redx/io/file_stream.hpp': No such file or directory	tdb_editor	C:\Users\lostl\GitHub\CyberpunkSaveEditor-0.6.0-alpha\source\redx\tweakdb\tweakdb.hpp	12

**Comment by PixelRick** [comment]
The whole solution includes optional tools such as cpfs, and this one is broken on master for now. You can build the editor individually. I reserved my next week-end to do the update and a bit of clean-up.

**Comment by LostLogic** [comment]
I see. Thanks for the feedback @PixelRick and for scheduling time to update the project for 1.6.
Hoping to fix an issue with my save file from PS5 - With the sync I can now access it through PC, so it might be possible to change it, sync it from PC to cloud then continue on at the PS5.

**Comment by PixelRick** [comment]
I am on it today ;)
