### ISSUE TITLE
Saves not loading

### ISSUE THREAD

**Issue by jeremysanders** [PixelRick/CyberpunkSaveEditor#44]
I get the following error when trying to load my saves with the latest releases:
![Capture](https://user-images.githubusercontent.com/274711/192102981-23277ec1-6dfa-42ad-953c-c5d45619ec05.PNG)

Any ideas?

**Comment by PixelRick** [comment]
Current version doesn't support 1.6 types. Please wait for the update of the tool. Follow #41 for info.
