### ISSUE TITLE
Excessive RAM usage from the program utilizing until available RAM is depleted on Windows 11

### ISSUE THREAD

**Issue by dstn-idly** [PixelRick/CyberpunkSaveEditor#45]
Hello!

Ever since making a new character to swap character presets. Whenever I try to open the old character save file, it causes it to use excessive RAM. This is with the new 1.6 update. 

Here is a save file reference and a screenshot below.

[ManualSave-13.zip](https://github.com/PixelRick/CyberpunkSaveEditor/files/9659922/ManualSave-13.zip)

![image](https://user-images.githubusercontent.com/18632372/192646494-d34356fa-edb4-4d08-a55a-17261f38c2d5.png)

![image](https://user-images.githubusercontent.com/18632372/192646527-cfbf2e0a-1720-4f34-9589-affd3ab05ad3.png)

**Comment by szl0834** [comment]
same problem on win10 21h2 with cp ver 1.6

**Comment by HolidayTheBoi** [comment]
I second this on Windows 10, seems to be a problem when loading the node inventory. It actually full crashed my computer lmao

**Comment by PixelRick** [comment]
Follow issue #41 for updates.
