### ISSUE TITLE
cant load node_t PSData

### ISSUE THREAD

**Issue by Method-Development** [PixelRick/CyberpunkSaveEditor#56]
I just keep getting "couldn't load node_t PSData
reason: CObject::serialize_in: serial field
gameConstantStatModifierData::statType is missing from bp fields
![cp2077_issue_Capture](https://github.com/PixelRick/CyberpunkSaveEditor/assets/13261012/c4a4a06f-ba88-4da9-a45c-545b12311002)
[cp2077_sav.dat.txt](https://github.com/PixelRick/CyberpunkSaveEditor/files/11716517/cp2077_sav.dat.txt)

**Comment by PixelRick** [comment]
Hola, currently not maintaining the editor. Please use the wolvenkit.

**Comment by PixelRick** [comment]
PSData has been replaced by PersistencySystem2. This warning won't appear again.
