### ISSUE TITLE
Scriptable Systems object window entirely empty.

### ISSUE THREAD

**Issue by karinaquill** [PixelRick/CyberpunkSaveEditor#58]
![image](https://github.com/PixelRick/CyberpunkSaveEditor/assets/146596687/5100cda8-86b1-45d9-971e-2c50a2499b01)

**Comment by renifer18** [comment]
Did you find a solution to this problem? I have the same thing.

**Comment by PixelRick** [comment]
Hola, I probably have to do an update.. I am on Starfield these days so it may take some time. I know that the wkit-derived save editor is maintained, have you tried it ?

**Comment by snbsjshhs** [comment]
bro never updated it ☠️ i rly wanna test commands but script section is blank is there an alternative?

**Comment by PixelRick** [comment]
They changed this system multiple times and I didn't update for it. I do believe it's editable with the WKit since seberoth updated this part not long ago.

**Comment by snbsjshhs** [comment]
woah appreciate the quick reply hope you doing well. can you please link me that? I have ps4 sav.file and I need to run a script "RPGManager.ForceEquipItemOnPlayer(GetPlayer(),"Items.PlayerSilverhandArm", true)" or something like that it basically forces equip Johnny's arm to my character. I've seen the CET but it's for pc only so could you gimme a hand please?

**Comment by PixelRick** [comment]
Let's say you find 10ppl who really want me to update my editor then I'll probably commit to it. But I believe the wkit and scripts are now the way to go for most problems.

**Comment by snbsjshhs** [comment]
I know a few don't worry and why 10 people? your save editor is pretty helpful for ps4 and ps5 players not everyone owns a 4000$ pc wouldn't you think people would like that? I'm not sure what stopped you from updating it could be personal life or your lost motivation but your tool is known you just gotta update it, he'll I'll be the first to advertise about it and I have connections with known ps4 saves channels they'll definitely make a video about your tool. you're doing great man.

**Comment by PixelRick** [comment]
The story is work and other projects, and the fact that someone was maintaining another editor.
I actually left a lot of code hanging locally, reworked the scripted classes to work similarly to the game ones.
I'm interested in finishing that part to reuse it for other projects.
Lemme download the game right now and will see if I can catch up with the changes.

Also, I applied to CDPR last month but they didn't review my application yet. It would make updating the editor a piece of cake, having access to the game source :)

**Comment by snbsjshhs** [comment]
getting accepted into CDPR would be a game changer. I appreciate you getting back into this and I hope you get accepted. at least it's good to hear you're doing well.

**Comment by PixelRick** [comment]
> woah appreciate the quick reply hope you doing well. can you please link me that? I have ps4 sav.file and I need to run a script "RPGManager.ForceEquipItemOnPlayer(GetPlayer(),"Items.PlayerSilverhandArm", true)" or something like that it basically forces equip Johnny's arm to my character. I've seen the CET but it's for pc only so could you gimme a hand please?

Missed this message. Maybe saves can be edited with the wkit:
https://wiki.redmodding.org/wolvenkit/wolvenkit-app/editor/file-editor
If you have time to check it out and tell me, otherwise I'll be able to check myself in the coming days.

Fun fact, I just messed up and bought a gog key of Phantom liberty instead of a steam key --'

**Comment by PixelRick** [comment]
Ehm I think that for PlayerSilverhandArm you'll be able to use the inventory part, the scriptable systems was a different thing than you think.

**Comment by snbsjshhs** [comment]
I figured... it's more of a command actually. PlayerSilverhandArm will be in your inventory you just have to force equip it.

**Comment by snbsjshhs** [comment]
my brain is fried but I'll give that link a chance much appreciated! lmao I never knew there was separate keys

**Comment by snbsjshhs** [comment]
yeah I'm beat. I've really tried everything, even tried to equip Johnny's hand into V's body somehow didn't work. anyhow do you accept donations?

**Comment by PixelRick** [comment]
Ok, first I am going to check if the change can be persistent with saves or not.
I found a few saves online claiming they have the arm equipped.
If yes, I'll diff the change to identify where it's written.
If not, I'll see if there is a way to add scripts in saves somehow (that hasn't been done afaik, only script data).

**Comment by snbsjshhs** [comment]
noted. I'm available if you got a sav.dat I could import and test it out

**Comment by PixelRick** [comment]
It looks like the change is saved. I made two saves around the ForceEquip command.
So now I am going to fix the editor to do that in priority.

**Comment by PixelRick** [comment]
Fixed in v0.6.1-alpha
