### ISSUE TITLE
Some Quest Items added through console Staying flagged 

### ISSUE THREAD

**Issue by MrButterfl7** [PixelRick/CyberpunkSaveEditor#6]
And being unable to unequip them.

**Comment by Psype** [comment]
@MrButterfl7 Hi can you give some examples ? Did you applied the method on various inventories you have ? 

See, I have many of them. It has to be done on all of them separately.
![image](https://user-images.githubusercontent.com/13078156/103475061-3e4dd780-4daa-11eb-881a-d57c64993453.png)

Cheers

**Comment by MrButterfl7** [comment]
Yes I tried on all inventories. For example one of Johnny’s pants stay flagged. Or judy’s diving suit.

Sent from my iPhone

On 3 Jan 2021, at 09:00, Psype <notifications@github.com> wrote:

﻿

@MrButterfl7<https://github.com/MrButterfl7> Hi can you give some examples ? Did you applied the method on various inventories you have ?

See, I have many of them. It has to be done on all of them separately.
[image]<https://user-images.githubusercontent.com/13078156/103475061-3e4dd780-4daa-11eb-881a-d57c64993453.png>

Cheers

**Comment by PixelRick** [comment]
It is believed that those are special items, re-given on save load by game scripts based on game facts. It may be possible later to bypass it. It is also possible that future game updates will remove these scripts, probably there to patch faulty quest logic.

**Comment by Psype** [comment]
I got that issue, the flag was at 02 instead of 01. 
I guess that's why your button didn't caught them.

**Comment by PixelRick** [comment]
Added a checkbox for this second flag. The "unflag all" won't change it though as it is not yet fully understood what this flag means.
