### ISSUE TITLE
[Suggestion] Simple cleanup (deleting all food/drinks items)

### ISSUE THREAD

**Issue by Psype** [PixelRick/CyberpunkSaveEditor#7]
Hey there,

You editor is really good. I would suggest some tab/menu with pre-recorded modifications, such as deleting useless items, setting up money/craft items stock up, adding custom item and so on.

I'm fed up having those, and the recycling time quth the quantity selector is painful

![image](https://user-images.githubusercontent.com/13078156/103475357-d5b42a00-4dac-11eb-861f-815567942994.png)

cheers

**Comment by Psype** [comment]
Closing it as there's mods to do that... It wasn't needed to be related to saves edit.
Thanks guys

**Comment by PixelRick** [comment]
Still useful for console players.
