### ISSUE TITLE
[Feature request] UI button in navigation for %username%\Saved Games\

### ISSUE THREAD

**Issue by vaporwave9** [PixelRick/CyberpunkSaveEditor#8]
If you add a button to %username%\Saved Games\ you can jump directly into C:\Users\MyUsername\Saved Games\
Of course that is nagging on high level, I just think it would help some people navigate on first launch easier ;)
Love your tool and thanks for still coding for so long!

**Comment by SkillerCMP** [comment]
Defaulting to this directory - would be bad for the Ps4 saves but a UI button to jump to directory, or Adding Ability to Drag and Drop save onto EXE.

**Comment by XxUnkn0wnxX** [comment]
drag & drop sounds good ;)

**Comment by PixelRick** [comment]
I had little time to work on this, but I will do my best to merge the PR and try adding drag&drop for v0.5.3

**Comment by PixelRick** [comment]
Drag&drop have been implemented in 30c7251d9046b3820adcb5107b7863cfdc4992f3 and goto buttons for the open dialog in 786ba1d018f67ec66c5b4a5cdf646eb5c20bac9b (using PR #9).
Available in next hotfix release (v0.5.2-alpha.2)
